# Generated by Django 5.1.7 on 2025-05-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votoencuesta',
            name='valor',
            field=models.CharField(choices=[('1', 'No me gustó'), ('2', 'Me gustó poco'), ('3', 'Me gustó'), ('4', 'Me gustó mucho')], max_length=1),
        ),
    ]
