# Generated by Django 5.1.7 on 2025-04-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='mensaje_error',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje si responde mal'),
        ),
    ]
