runtime: python311
entrypoint: gunicorn -b :$PORT plataforma_interactiva.wsgi

handlers:
- url: /static
  static_dir: staticfiles/

- url: /.*
  script: auto

env_variables:
  DJANGO_ENV: "production"
  DJANGO_SETTINGS_MODULE: "plataforma_interactiva.settings"
  DB_NAME: plataforma_interactiva
  DB_USER: postgres
  DB_PASSWORD: Fede6866
  INSTANCE_CONNECTION_NAME: plataforma-interactiva-2025:southamerica-east1:scs-db

beta_settings:
  cloud_sql_instances: plataforma-interactiva-2025:southamerica-east1:scs-db
